OC.L10N.register(
  "onlyoffice",
  {
    "Access denied" : "Không có quyền truy cập",
    "Invalid request" : "Yêu cầu không hợp lệ",
    "Files not found" : "Tệp tin không tồn tại",
    "File not found" : "Tập tin không tồn tại",
    "Not permitted" : "Không được phép",
    "Download failed" : "Tải về thất bại",
    "The required folder was not found" : "Thư mục không tồn tại",
    "You don't have enough permission to create" : "Bạn không có quyền được tạo",
    "Template not found" : "Biểu mẫu không tồn tại",
    "Can't create file" : "Không thể tạo tệp tin",
    "Format is not supported" : "Định dạng không được hỗ trợ",
    "Conversion is not required" : "Không yêu cầu chuyển đổi",
    "Failed to download converted file" : "Tải tập tin chuyển đổi thất bại",
    "ONLYOFFICE app is not configured. Please contact admin" : "Ứng dụng Office chưa được cấu hình. Hãy liên hệ với quản trị viên",
    "FileId is empty" : "Id của tệp tin không được để trống",
    "You do not have enough permissions to view the file" : "Bạn không có quyền được xem tệp tin này",
    "Error occurred in the document service" : "Dịch vụ Tài liệu xuất hiện lỗi",
    "Not supported version" : "Phiên bản không được hỗ trợ",
    "ONLYOFFICE cannot be reached. Please contact admin" : "Không truy cập được Office. Hãy liên hệ với quản trị viên",
    "Loading, please wait." : "Đang tải, hãy chờ một lát.",
    "File created" : "Tệp tin đã được tạo thành công",
    "Open in ONLYOFFICE" : "Mở trong Office",
    "Convert with ONLYOFFICE" : "Chuyển đổi bằng Office",
    "Document" : "Tài liệu",
    "Spreadsheet" : "Trang tính",
    "Presentation" : "Trang trình bày",
    "Error when trying to connect" : "Có lỗi xảy ra trong quá trình kết nối",
    "Settings have been successfully updated" : "Cài đặt đã được cập nhật thành công",
    "Server can't read xml" : "Máy chủ không đọc được XML",
    "Bad Response. Errors: " : "Lỗi phản hồi",
    "Documentation" : "Tài liệu",
    "ONLYOFFICE Document Service Location specifies the address of the server with the document services installed. Please change the '<documentserver>' for the server address in the below line." : "Tính năng Định vị dịch vụ Tài liệu của Office mô tả địa chỉ máy chủ chạy dịch vụ Tài liệu. Hãy thay đổi mục '<documentserver>' với địa chỉ tương ứng",
    "Document Editing Service address" : "Địa chỉ của dịch vụ Chỉnh sửa tài liệu",
    "Advanced server settings" : "Các cài đặt máy chủ nâng cao",
    "Document Editing Service address for internal requests from the server" : "Địa chỉ dịch vụ Chỉnh sửa Tài liệu để thực hiện các các yêu cầu nội bộ từ máy chủ",
    "Server address for internal requests from the Document Editing Service" : "Địa chỉ máy chủ xử lý các yêu cầu nội bộ cho dịch vụ Chỉnh sửa Tài liệu",
    "Secret key (leave blank to disable)" : "Khóa bảo mật (Bỏ trống để vô hiệu hóa)",
    "Open file in the same tab" : "Mở tệp tin ở trên tab này",
    "The default application for opening the format" : "Ứng dụng mặc định để mở định dạng này",
    "Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)" : "Chỉnh sửa tệp tin (Do hạn chế về định dạng, dữ liệu sau khi lưu lại có thể bị mất nếu lựa chọn một trong các định dạng dưới đây)",
    "View details" : "Xem chi tiết",
    "Save" : "Lưu lại",
    "Mixed Active Content is not allowed. HTTPS address for Document Server is required." : "Tính năng Nội dung hoạt động hỗn hợp không được phép kích hoạt. Máy chủ Tài liệu chưa có địa chỉ HTTPS",
    "Restrict access to editors to following groups" : "Chỉ có phép quyền chỉnh sửa cho các các nhóm sau",
    "Server settings" : "Cấu hình máy chủ",
    "Common settings" : "Cấu hình chung",
    "Editor customization settings" : "Cấu hình tùy chọn của Người chỉnh sửa",
    "The customization section allows personalizing the editor interface" : "Mục tùy chọn cho phép thay đổi giao diện chỉnh sửa theo ý muốn",
    "Display Chat menu button" : "Hiển thị nút Menu trò chuyện",
    "Display the header more compact" : "Thu gọn đầu mục",
    "Display Feedback & Support menu button" : "Hiển thị nút Menu Phản hồi & Hỗ trợ",
    "Display Help menu button" : "Hiển thị nút Menu trợ giúp",
    "Display monochrome toolbar header" : "Hiển thị thanh đầu mục đơn sắc",
    "Save as" : "Lưu thành",
    "File saved" : "Tệp tin được lưu thành công",
    "Insert image" : "Chèn ảnh",
    "Select recipients" : "Chọn người nhận",
    "Connect to demo ONLYOFFICE Document Server" : "Kết nối đến máy chủ Office Tài liệu - bản demo",
    "This is a public test server, please do not use it for private sensitive data. The server will be available during a 30-day period." : "Đây là máy chủ chạy thử, vui lòng không sử dụng cho dữ liệu riêng nhạy cảm. Máy chủ sẽ hoạt động trong vòng 30 ngày",
    "The 30-day test period is over, you can no longer connect to demo ONLYOFFICE Document Server." : "Thời hạn chạy thử 30 ngày đã hết, bạn sẽ không thể kết nối đến máy chủ Office Tài liệu nữa",
    "You are using public demo ONLYOFFICE Document Server. Please do not store private sensitive data." : "Bạn đang sử dụng Office Tài liệu bản chạy thử. Vui lòng không lưu trữ dữ liệu nhạy cảm",
    "Secure view settings" : "Cài đặt cho chế độ xem an toàn",
    "Secure view enables you to secure documents by embedding a watermark" : "Chế độ xem an toàn giúp bạn bảo vệ tài liệu bằng cách nhúng watermark",
    "Enable watermarking" : "Bật tính năng watermark",
    "Watermark text" : "Nội dung watermark",
    "DO NOT SHARE THIS" : "KHÔNG CHIA SẺ",
    "Show watermark on tagged files" : "Hiển thị watermark trên các tệp tin đã đánh dấu",
    "Show watermark for users of groups" : "Hiển thị watermark cho người dùng thuộc các nhóm",
    "Supported placeholders" : "Các gợi ý được hỗ trợ",
    "Show watermark for all shares" : "Hiển thị watermark cho tất cả các loại chia sẻ",
    "Show watermark for read only shares" : "Hiển thị watermark cho các chia sẻ chỉ cho phép đọc",
    "Link shares" : "Liên kết chia sẻ",
    "Show watermark for all link shares" : "Hiển thị watermark cho tất cả các liên kết chia sẻ",
    "Show watermark for download hidden shares" : "Hiển thị watermark cho các chia sẻ tải ẩn",
    "Show watermark for read only link shares" : "Hiển thị watermark cho các chia sẻ chỉ cho phép đọc",
    "Show watermark on link shares with specific system tags" : "Hiển thị watermark cho các liên kết chia sẻ với các nhãn cụ thể",
    "Select tag" : "Lựa chọn nhãn",
    "Select file to compare" : "Chọn tệp tin để so sánh",
    "Review mode for viewing": "Chế độ xem lại",
    "Markup": "Đánh dấu",
    "Final": "Cuối cùng",
    "Original": "Bản gốc",
    "version": "Phiên bản",
    "Disable certificate verification (insecure)": "Tắt xác thực chứng chỉ (không bảo mật)",
    "Keep intermediate versions when editing (forcesave)": "Tự động lưu phiên bản khi chỉnh sửa",
    "Use ONLYOFFICE to generate a document preview (it will take up disk space)": "Sử dụng Office để tạo bản xem trước (tùy chọn này sẽ tốn bộ nhớ)",
    "Keep metadata for each version once the document is edited (it will take up disk space)": "Giữ metada cho từng phiên bản khi tài liệu được chỉnh sửa (tùy chọn này sẽ tốn bộ nhớ)",
    "All history successfully deleted": "Mọi lịch sử đã được xóa thành công",
    "Create": "Tạo",
    "Select template" : "Chọn bản mẫu",
    "Invalid file provided" : "Tệp tin được cung cấp không hợp lệ",
    "Empty": "Trống",
    "Error" : "Lỗi",
    "Add a new template": "Thêm một bản mẫu",
    "Template already exists": "Bản mẫu đã tồn tại",
    "Template must be in OOXML format": "Bản mẫu phải được viết dưới định dạng OOXML",
    "Template successfully added": "Bản mẫu được thêm thành công",
    "Template successfully deleted": "Bản mẫu được xóa thành công",
    "Common templates": "Bản mẫu chung",
    "Failed to delete template": "Xóa bản mẫu thất bại"
  },
  "nplurals=2; plural=(n != 1);");