version: '3.7'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - mariadb
    environment:
      - MYSQL_HOST=nextcloud-mariadb
    env_file:
      - env
    networks:
      - nextcloud-nextwork
    restart: always

  mariadb:
    image: mariadb
    container_name: nextcloud-mariadb
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - env
    networks:
      - nextcloud-nextwork
    restart: always

  collabora:
    image: collabora/code
    container_name: nextcloud-collabora
    volumes:
      - collabora:/etc/loolwsd
    ports:
      - 9980:9980
    environment:
      - username=admin
      - password=admin
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false
    env_file:
      - env
    networks:
      - nextcloud-nextwork
    restart: always

volumes:
  nextcloud:
    external: true
  mysql:
    external: true
  collabora:
    external: true

networks:
  nextcloud-nextwork:
