version: '3.7'

services:
  nextcloud:
    image: binhnv56/nextcloud:v21.0.0-vi
    container_name: nextcloud
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - mariadb
    environment:
      - MYSQL_HOST=nextcloud-mariadb
    env_file:
      - env
    # - proxy
    networks:
      - nextcloud-nextwork
    restart: always

  mariadb:
    image: mariadb
    container_name: nextcloud-mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - env
    networks:
      - nextcloud-nextwork
    restart: always

  collabora:
    image: collabora/code
    container_name: nextcloud-collabora
    ports:
      - 9980:9980
    environment:
      - username=admin
      - password=admin
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false # without ssl
    env_file:
      - env
    networks:
      - nextcloud-nextwork
    restart: always

volumes:
  nextcloud:
    external: true
  mariadb:
    external: true

networks:
  nextcloud-nextwork:
