version: '3.7'

services:
  nextcloud:
    image: binhnv56/nextcloud
    container_name: nextcloud
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - mariadb
    environment:
      - MYSQL_HOST=nextcloud-mariadb
    env_file:
      - env/web.env
      - env/db.env
    # - env/proxy.env
    networks:
      - nextcloud-network
    restart: always

  mariadb:
    image: mariadb
    container_name: nextcloud-mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - env/db.env
    networks:
      - nextcloud-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nextcloud-phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: nextcloud-mariadb
    networks:
      - nextcloud-network
    restart: always

  collabora:
    image: binhnv56/collabora
    container_name: nextcloud-collabora
    ports:
      - 9980:9980
    environment:
      - domain=habeco.vworkspace.cloud
      - username=admin
      - password=admin
    # - extra_params=--o:user_interface.mode=classic
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false --o:user_interface.mode=classic # without ssl
    networks:
      - nextcloud-network
    restart: always

volumes:
  nextcloud:
  mariadb:

networks:
  nextcloud-network:
     external: true
