OC.L10N.register(
    "quicknotes",
    {
    "Quick notes" : "Ghi chú nhanh",
    "Tag the note" : "Gắn thẻ ghi chú",
    "Enter tags to organize your note" : "Nhập thẻ để sắp xếp ghi chú",
    "Enter tag name" : "Nhập tên thẻ",
    "Cancel" : "Hủy",
    "Done" : "Hoàn thành",
    "Tags" : "Thẻ",
    "Save" : "Lưu",
    "Looking for your notes" : "Tìm kiếm ghi chú của bạn",
    "Nothing here. Take your first quick notes" : "Tạo ghi chú đầu tiên!",
    "Are you sure you want to delete the note?" : "Bạn có chắc chắn muốn xóa ghi chú?",
    "Delete note" : "Xóa ghi chú",
    "Unpin note" : "Bỏ ghim ghi chú",
    "Pin note" : "Ghim ghi chú",
    "Do you want to discard the changes?" : "Bạn có muốn hủy bỏ thay đổi?",
    "Unsaved changes" : "Thay đổi chưa lưu",
    "Select file to attach" : "Chọn file để đính kèm",
    "New note" : "Ghi chú mới",
    "All notes" : "Tất cả ghi chú",
    "Colors" : "Màu",
    "Notes" : "Ghi chú",
    "Bold" : "Đậm",
    "Italic" : "Nghiêng",
    "Underline" : "Gạch dưới",
    "Strikethrough" : "Gạch đè",
    "Bulleted list" : "Danh sách có dấu đầu dòng",
    "Numbered list" : "Danh sách đánh số",
    "Blockquote" : "Trích dẫn",
    "Clean format" : "Xóa định dạng",
    "Quick notes with a basic rich text" : "Ghi chú nhanh với văn bản rich cơ bản",
    "No tags found" : "Không tìm thấy thẻ",
    "Share note" : "Chia sẻ ghi chú",
    "Select the users to share. By default you only share the note. Attachments should be shared from files so they can view it." : "Chọn người dùng để chia sẻ. Theo mặc định ban đầu ghi chú chỉ chia sẻ với ban. Đính kèm nên được chia sẻ từ file để họ có thể thấy.",
    "Select the users to share" : "Chọn người dùng để chia sẻ",
    "No user found" : "Không tìm thấy người dùng",
    "Shared with {user}" : "Được chia sẻ với {user}",
    "Shared by {user}" : "Được chia sẻ bởi {user}",
    "Delete attachment" : "Xóa đính kèm",
    "Attach file" : "File đính kèm",
    "Shared" : "Được chia sẻ",
    "Shared with others" : "Được chia sẻ với người khác",
    "Shared with you" : "Được chia sẻ với bạn",
    "Close" : "Đóng",
    "Default color for new notes" : "Màu mặc định cho ghi chú mới",
    "Settings" : "Cài đặt"
},
"nplurals=2; plural=(n > 1);");